type: scalar

# Short text description of the data you are providing.
description: City of Chicago Beach Weather Stations - Automated Sensors - 2015 - Solar Radiation

poweredBy: '<a href="https://data.cityofchicago.org/"><img src="https://data.cityofchicago.org/stylesheets/images/domains/data.cityofchicago.org/chicago_logo.png"></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/Chicago

soda:
- source: data.cityofchicago.org
  dataset: 77jv-5zb8
  limit: 100

# How often should River View poll your data sources?
interval: 1 hour

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 1 year

# Primary data, usually collected in one location. Should both be scalar values.
fields:
- solar_radiation
- barometric_pressure
- wind_direction
- interval_rain
- wind_speed
- wet_bulb_temperature
- air_temperature
- humidity
- precipitation_type
- total_rain
- maximum_wind_speed
- heading
- rain_intensity

# This provides more information about the data. This data doesn't change over
# time like the fields.
metadata:
- station_name
- battery_life
